# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'case.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import Examiner


class Ui_NewCaseINformation(object):
    def setupUi(self, NewCaseINformation):
        NewCaseINformation.setObjectName("NewCaseINformation")
        NewCaseINformation.resize(867, 594)
        NewCaseINformation.setStyleSheet("size=20")
        self.BtnBackCase = QtWidgets.QPushButton(NewCaseINformation)
        self.BtnBackCase.setGeometry(QtCore.QRect(310, 540, 93, 28))
        self.BtnBackCase.setObjectName("BtnBackCase")
        self.BtnNextCase = QtWidgets.QPushButton(NewCaseINformation)
        self.BtnNextCase.setGeometry(QtCore.QRect(420, 540, 93, 28))
        self.BtnNextCase.setObjectName("BtnNextCase")
        self.BtnFinshCase = QtWidgets.QPushButton(NewCaseINformation)
        self.BtnFinshCase.setGeometry(QtCore.QRect(530, 540, 93, 28))
        self.BtnFinshCase.setObjectName("BtnFinshCase")
        self.BtnCancleCase = QtWidgets.QPushButton(NewCaseINformation)
        self.BtnCancleCase.setGeometry(QtCore.QRect(630, 540, 93, 28))
        self.BtnCancleCase.setObjectName("BtnCancleCase")
        self.BrowsCase = QtWidgets.QPushButton(NewCaseINformation)
        self.BrowsCase.setGeometry(QtCore.QRect(670, 120, 93, 28))
        self.BrowsCase.setObjectName("BrowsCase")
        self.label = QtWidgets.QLabel(NewCaseINformation)
        self.label.setGeometry(QtCore.QRect(150, 60, 161, 31))
        self.label.setStyleSheet("font-size:12pt")
        self.label.setObjectName("label")
        self.LnEdtCaseName = QtWidgets.QLineEdit(NewCaseINformation)
        self.LnEdtCaseName.setGeometry(QtCore.QRect(300, 70, 361, 22))
        self.LnEdtCaseName.setObjectName("LnEdtCaseName")
        self.label_2 = QtWidgets.QLabel(NewCaseINformation)
        self.label_2.setGeometry(QtCore.QRect(140, 100, 151, 51))
        self.label_2.setStyleSheet("font-size:12pt")
        self.label_2.setObjectName("label_2")
        self.LnEdtBaseDirectorey = QtWidgets.QLineEdit(NewCaseINformation)
        self.LnEdtBaseDirectorey.setGeometry(QtCore.QRect(300, 120, 361, 22))
        self.LnEdtBaseDirectorey.setObjectName("LnEdtBaseDirectorey")
        self.RadSingleEmail = QtWidgets.QRadioButton(NewCaseINformation)
        self.RadSingleEmail.setGeometry(QtCore.QRect(280, 170, 141, 20))
        self.RadSingleEmail.setStyleSheet("font-size:12pt")
        self.RadSingleEmail.setObjectName("RadSingleEmail")
        self.RadMultiEmail = QtWidgets.QRadioButton(NewCaseINformation)
        self.RadMultiEmail.setGeometry(QtCore.QRect(440, 170, 131, 16))
        self.RadMultiEmail.setStyleSheet("font-size:12pt")
        self.RadMultiEmail.setObjectName("RadMultiEmail")
        self.label_3 = QtWidgets.QLabel(NewCaseINformation)
        self.label_3.setGeometry(QtCore.QRect(160, 170, 91, 21))
        self.label_3.setStyleSheet("font-size:12pt")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(NewCaseINformation)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 121, 21))
        self.label_4.setStyleSheet("font-size:12pt\n"
"")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.BtnHelpCase = QtWidgets.QPushButton(NewCaseINformation)
        self.BtnHelpCase.setGeometry(QtCore.QRect(730, 540, 93, 28))
        self.BtnHelpCase.setObjectName("BtnHelpCase")

        self.retranslateUi(NewCaseINformation)
        QtCore.QMetaObject.connectSlotsByName(NewCaseINformation)
        self.BtnNextCase.clicked.connect(self.nextpage)




    def retranslateUi(self, NewCaseINformation):
        _translate = QtCore.QCoreApplication.translate
        NewCaseINformation.setWindowTitle(_translate("NewCaseINformation", "Dialog"))
        self.BtnBackCase.setText(_translate("NewCaseINformation", "Back"))
        self.BtnNextCase.setText(_translate("NewCaseINformation", "Next"))
        self.BtnFinshCase.setText(_translate("NewCaseINformation", "Finish"))
        self.BtnCancleCase.setText(_translate("NewCaseINformation", "Cancel"))
        self.BrowsCase.setText(_translate("NewCaseINformation", "Browse"))
        self.label.setText(_translate("NewCaseINformation", "Case Name:"))
        self.label_2.setText(_translate("NewCaseINformation", "BaseDirectorey:"))
        self.RadSingleEmail.setText(_translate("NewCaseINformation", "single email"))
        self.RadMultiEmail.setText(_translate("NewCaseINformation", "Multi-Emeil"))
        self.label_3.setText(_translate("NewCaseINformation", "case Type"))
        self.BtnHelpCase.setText(_translate("NewCaseINformation", "Help"))
    def nextpage(self):

        self.Dialog = QtWidgets.QDialog()
        self.ui = Examiner.Ui_Dialog()
        self.ui.setupUi(self.Dialog)
        self.Dialog.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewCaseINformation = QtWidgets.QDialog()
    ui = Ui_NewCaseINformation()
    ui.setupUi(NewCaseINformation)
    NewCaseINformation.show()
    sys.exit(app.exec_())


