# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\samar\Desktop\finalyearproject\pythonProject1\view\analysis.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import PIL.ImageGrab
from PyQt5.QtWebEngineWidgets import QWebEngineView
#from GeographicalLocation import *
from cases import *

 
from peoples import People

from viber import viber
from GeographicalLocation import MyApp

from socialNetwork import*
CustomObjectRole=QtCore.Qt.UserRole + 1
class Ui_DialogAnalysis(object):

    def __init__(self, ex = None):
        self.case =cases ()
        super(Ui_DialogAnalysis,self).__init__()
        if ex == None:
           return
        
        self.Case = ex  
        self.SocialNetwork= SocialNetwork()    
        self.activepeople = People()  
        self.viber=viber()
        
        
    @property
    def viber(self):
        return self.viber

    @viber.setter
    def viber(self, value):
        self.viber = value
    
    
    @property
    def Case(self):
        return self.case

    @Case.setter
    def Case(self, value):
        self.case = value

    @property
    def activepeople(self):
        return self.activepeople
    @activepeople.setter
    def activepeople(self, value):
        self.activepeople = value
    @property
    def SocialNetwork(self):
        return self.SocialNetwork

    @SocialNetwork.setter
    def SocialNetwork(self, value):
        self.SocialNetwork = value
    def setupUi(self, DialogAnalysis):
        DialogAnalysis.setObjectName("DialogAnalysis")
        DialogAnalysis.resize(1482, 1003)
        self.tabWidgetBookMark = QtWidgets.QTabWidget(DialogAnalysis)
        self.tabWidgetBookMark.setGeometry(QtCore.QRect(290, 0, 1011, 1001))
        self.tabWidgetBookMark.setObjectName("tabWidgetBookMark")
        self.geoloctab = QtWidgets.QWidget()
        self.geoloctab.setObjectName("geoloctab")
        self.tabWidgetBookMark.addTab(MyApp(), "geo")
       
        self.SocialNetworktab = QtWidgets.QWidget()
        self.SocialNetworktab.setObjectName("SocialNetworktab")
        # visualization
        self.lbl_Visualization = QtWidgets.QLabel(self.SocialNetworktab)
        self.lbl_Visualization.setGeometry(QtCore.QRect(14, 20, 971, 711))
        self.lbl_Visualization.setText("")
        self.lbl_Visualization.setPixmap(QtGui.QPixmap("c:\\Users\\samar\\Desktop\\finalyearproject\\pythonProject1\\view\\filename4.png"))
        self.lbl_Visualization.setScaledContents(True)
        self.lbl_Visualization.setObjectName("lbl_Visualization")
        self.groupBox_7 = QtWidgets.QGroupBox(self.SocialNetworktab)
        self.groupBox_7.setGeometry(QtCore.QRect(30, 780, 751, 80))
        self.groupBox_7.setObjectName("groupBox_7")
        self.btn_Circular_Layout = QtWidgets.QPushButton(self.groupBox_7)
        self.btn_Circular_Layout.setGeometry(QtCore.QRect(30, 30, 93, 28))
        self.btn_Circular_Layout.setObjectName("btn_Circular_Layout")
        self.btn_Planer_Layout = QtWidgets.QPushButton(self.groupBox_7)
        self.btn_Planer_Layout.setGeometry(QtCore.QRect(130, 30, 93, 28))
        self.btn_Planer_Layout.setObjectName("btn_Planer_Layout")
        self.btn_Random_Layout = QtWidgets.QPushButton(self.groupBox_7)
        self.btn_Random_Layout.setGeometry(QtCore.QRect(230, 30, 93, 28))
        self.btn_Random_Layout.setObjectName("btn_Random_Layout")
        self.btn_Special_Layout = QtWidgets.QPushButton(self.groupBox_7)
        self.btn_Special_Layout.setGeometry(QtCore.QRect(340, 30, 93, 28))
        self.btn_Special_Layout.setObjectName("btn_Special_Layout")
        self.tabWidgetBookMark.addTab(self.SocialNetworktab, "")
        self.statisictap = QtWidgets.QWidget()
        self.statisictap.setObjectName("statisictap")
        self.groupBox_4 = QtWidgets.QGroupBox(self.statisictap)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 790, 791, 80))
        self.groupBox_4.setObjectName("groupBox_4")
        self.btnPieChart = QtWidgets.QPushButton(self.groupBox_4)
        self.btnPieChart.setGeometry(QtCore.QRect(70, 20, 93, 28))
        self.btnPieChart.setObjectName("btnPieChart")
        self.btnBarChart = QtWidgets.QPushButton(self.groupBox_4)
        self.btnBarChart.setGeometry(QtCore.QRect(210, 20, 93, 28))
        self.btnBarChart.setObjectName("btnBarChart")
        self.checkBox_places = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_places.setGeometry(QtCore.QRect(410, 20, 81, 20))
        self.checkBox_places.setObjectName("checkBox_places")
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_5.setGeometry(QtCore.QRect(530, 20, 81, 20))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_6.setGeometry(QtCore.QRect(670, 20, 81, 20))
        self.checkBox_6.setObjectName("checkBox_6")
        self.lbl_statistic = QtWidgets.QLabel(self.statisictap)
        self.lbl_statistic.setGeometry(QtCore.QRect(20, 20, 761, 751))
        self.lbl_statistic.setText("")
        self.lbl_statistic.setPixmap(QtGui.QPixmap("c:\\Users\\samar\\Desktop\\finalyearproject\\pythonProject1\\view\\barchart.png"))
        self.lbl_statistic.setScaledContents(True)
        self.lbl_statistic.setObjectName("lbl_statistic")
        self.tabWidgetBookMark.addTab(self.statisictap, "")
        self.tab_tap = QtWidgets.QWidget()
        self.tab_tap.setObjectName("tab_tap")
        self.label_5 = QtWidgets.QLabel(self.tab_tap)
        self.label_5.setGeometry(QtCore.QRect(-20, -10, 951, 871))
        self.label_5.setObjectName("label_5")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_tap)
        self.plainTextEdit.setGeometry(QtCore.QRect(0, 100, 961, 761))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.tabWidgetBookMark.addTab(self.tab_tap, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 821, 821))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lbl_fileName = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_fileName.setObjectName("lbl_fileName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_fileName)
        self.lineEdit_fIstName = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_fIstName.setObjectName("lineEdit_fIstName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_fIstName)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_Lable = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_Lable.setObjectName("lineEdit_Lable")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Lable)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_BookMarkNumber = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_BookMarkNumber.setObjectName("lineEdit_BookMarkNumber")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_BookMarkNumber)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lineEdit_from = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_from.setObjectName("lineEdit_from")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_from)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.lineEdit_to = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_to.setObjectName("lineEdit_to")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_to)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.lineEdit_CC = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_CC.setObjectName("lineEdit_CC")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_CC)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.lineEdit_Bcc = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_Bcc.setObjectName("lineEdit_Bcc")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Bcc)
        self.lbl_AddCooment = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_AddCooment.setObjectName("lbl_AddCooment")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lbl_AddCooment)
        self.LnEdtAddCommant = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LnEdtAddCommant.setObjectName("LnEdtAddCommant")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.LnEdtAddCommant)
        self.pushButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.pushButton)
        self.tabWidgetBookMark.addTab(self.tab, "")
        self.dockWidget_analysis = QtWidgets.QDockWidget(DialogAnalysis)
        self.dockWidget_analysis.setGeometry(QtCore.QRect(0, -10, 295, 902))
        self.dockWidget_analysis.setStyleSheet("q rgb(250, 235, 255)")
        self.dockWidget_analysis.setObjectName("dockWidget_analysis")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.dockWidgetContents_2)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 140, 211, 151))
        self.groupBox_2.setObjectName("groupBox_2")
        self.checkBox_Email = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_Email.setGeometry(QtCore.QRect(30, 40, 81, 20))
        self.checkBox_Email.setObjectName("checkBox_Email")
        self.checkBox_WhatsApp = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_WhatsApp.setGeometry(QtCore.QRect(30, 70, 81, 20))
        self.checkBox_WhatsApp.setObjectName("checkBox_WhatsApp")
        self.checkBox_Viber = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_Viber.setGeometry(QtCore.QRect(30, 110, 81, 20))
        self.checkBox_Viber.setObjectName("checkBox_Viber")
        self.lineEdit_serchKeyWord_ForChat = QtWidgets.QLineEdit(self.dockWidgetContents_2)
        self.lineEdit_serchKeyWord_ForChat.setGeometry(QtCore.QRect(120, 90, 161, 31))
        self.lineEdit_serchKeyWord_ForChat.setObjectName("lineEdit_serchKeyWord_ForChat")
        self.btnKeyWordChat_2 = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.btnKeyWordChat_2.setGeometry(QtCore.QRect(10, 90, 111, 31))
        self.btnKeyWordChat_2.setObjectName("btnKeyWordChat_2")
        self.btnSnapshot = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.btnSnapshot.setGeometry(QtCore.QRect(20, 560, 61, 51))
        self.btnSnapshot.setObjectName("btnSnapshot")
        self.groupBox_3 = QtWidgets.QGroupBox(self.dockWidgetContents_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 640, 231, 81))
        self.groupBox_3.setObjectName("groupBox_3")
        self.checkBox_filterKeyWord = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_filterKeyWord.setGeometry(QtCore.QRect(10, 20, 201, 20))
        self.checkBox_filterKeyWord.setObjectName("checkBox_filterKeyWord")
        self.checkBox_FiterTimeDate = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_FiterTimeDate.setGeometry(QtCore.QRect(10, 50, 171, 20))
        self.checkBox_FiterTimeDate.setObjectName("checkBox_FiterTimeDate")
        self.btnVerify = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.btnVerify.setGeometry(QtCore.QRect(40, 760, 141, 28))
        self.btnVerify.setObjectName("btnVerify")
        self.groupBox_5 = QtWidgets.QGroupBox(self.dockWidgetContents_2)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 300, 271, 101))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setGeometry(QtCore.QRect(10, 20, 61, 20))
        self.label.setObjectName("label")
        self.dateEdit_dateFrom = QtWidgets.QDateEdit(self.groupBox_5)
        self.dateEdit_dateFrom.setGeometry(QtCore.QRect(80, 20, 110, 22))
        self.dateEdit_dateFrom.setObjectName("dateEdit_dateFrom")
        self.dateEdit_dateTo = QtWidgets.QDateEdit(self.groupBox_5)
        self.dateEdit_dateTo.setGeometry(QtCore.QRect(80, 60, 110, 22))
        self.dateEdit_dateTo.setObjectName("dateEdit_dateTo")
        self.groupBox_6 = QtWidgets.QGroupBox(self.dockWidgetContents_2)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 460, 241, 80))
        self.groupBox_6.setObjectName("groupBox_6")
        self.lineEdit_Sender = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_Sender.setGeometry(QtCore.QRect(70, 20, 161, 22))
        self.lineEdit_Sender.setObjectName("lineEdit_Sender")
        self.label_3 = QtWidgets.QLabel(self.groupBox_6)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 55, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_Recepian = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_Recepian.setGeometry(QtCore.QRect(70, 50, 161, 22))
        self.lineEdit_Recepian.setObjectName("lineEdit_Recepian")
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 55, 21))
        self.label_4.setObjectName("label_4")
        self.label_casename = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.label_casename.setGeometry(QtCore.QRect(100, 30, 81, 20))
        self.label_casename.setText("")
        self.label_casename.setObjectName("label_casename")
        self.label_6 = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.label_6.setGeometry(QtCore.QRect(40, 30, 55, 16))
        self.label_6.setObjectName("label_6")
        self.label_13 = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.label_13.setGeometry(QtCore.QRect(200, 30, 55, 16))
        self.label_13.setObjectName("label_13")
        self.dockWidget_analysis.setWidget(self.dockWidgetContents_2)

        self.retranslateUi(DialogAnalysis)
        self.tabWidgetBookMark.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(DialogAnalysis)

    def retranslateUi(self, DialogAnalysis):
        _translate = QtCore.QCoreApplication.translate
        DialogAnalysis.setWindowTitle(_translate("DialogAnalysis", "Dialog"))
        self.tabWidgetBookMark.setTabText(self.tabWidgetBookMark.indexOf(self.geoloctab), _translate("DialogAnalysis", "Geolocation"))
        self.groupBox_7.setTitle(_translate("DialogAnalysis", "Virtualization  Social Network"))
        self.btn_Circular_Layout.setText(_translate("DialogAnalysis", "Circular layout"))
        self.btn_Planer_Layout.setText(_translate("DialogAnalysis", "Planer layout"))
        self.btn_Random_Layout.setText(_translate("DialogAnalysis", "Random layout"))
        self.btn_Special_Layout.setText(_translate("DialogAnalysis", "Spectral layout"))
        self.tabWidgetBookMark.setTabText(self.tabWidgetBookMark.indexOf(self.SocialNetworktab), _translate("DialogAnalysis", "Social networ"))
        self.groupBox_4.setTitle(_translate("DialogAnalysis", "options"))
        self.btnPieChart.setText(_translate("DialogAnalysis", "Pie chart"))
        self.btnBarChart.setText(_translate("DialogAnalysis", "Bar chart"))
        self.checkBox_places.setText(_translate("DialogAnalysis", "Places"))
        self.checkBox_5.setText(_translate("DialogAnalysis", "People"))
        self.checkBox_6.setText(_translate("DialogAnalysis", "Dates"))
        self.tabWidgetBookMark.setTabText(self.tabWidgetBookMark.indexOf(self.statisictap), _translate("DialogAnalysis", "statisic"))
        self.label_5.setText(_translate("DialogAnalysis", "TextLabel"))
        self.tabWidgetBookMark.setTabText(self.tabWidgetBookMark.indexOf(self.tab_tap), _translate("DialogAnalysis", "chat"))
        self.lbl_fileName.setText(_translate("DialogAnalysis", " File Name"))
        self.label_7.setText(_translate("DialogAnalysis", " Lable"))
        self.label_8.setText(_translate("DialogAnalysis", " BookMark Number"))
        self.label_9.setText(_translate("DialogAnalysis", " From"))
        self.label_10.setText(_translate("DialogAnalysis", " To"))
        self.label_11.setText(_translate("DialogAnalysis", " cc"))
        self.label_12.setText(_translate("DialogAnalysis", " BCC"))
        self.lbl_AddCooment.setText(_translate("DialogAnalysis", "Add commant"))
        self.pushButton.setText(_translate("DialogAnalysis", "Submit"))
        self.tabWidgetBookMark.setTabText(self.tabWidgetBookMark.indexOf(self.tab), _translate("DialogAnalysis", "Bookmark"))
        self.dockWidget_analysis.setWindowTitle(_translate("DialogAnalysis", "Analysis bar"))
        self.groupBox_2.setTitle(_translate("DialogAnalysis", "platForm"))
        self.checkBox_Email.setText(_translate("DialogAnalysis", "Email"))
        self.checkBox_WhatsApp.setText(_translate("DialogAnalysis", "WahatApp"))
        self.checkBox_Viber.setText(_translate("DialogAnalysis", "Viber"))
        self.btnKeyWordChat_2.setText(_translate("DialogAnalysis", "Search keyword"))
        self.btnSnapshot.setText(_translate("DialogAnalysis", "Snapshot"))
        self.groupBox_3.setTitle(_translate("DialogAnalysis", "Filter option"))
        self.checkBox_filterKeyWord.setText(_translate("DialogAnalysis", "Filter by  keyword only"))
        self.checkBox_FiterTimeDate.setText(_translate("DialogAnalysis", "Filter by Date and time only"))
        self.btnVerify.setText(_translate("DialogAnalysis", "verify"))
        self.groupBox_5.setTitle(_translate("DialogAnalysis", "Date filtering"))
        self.label_2.setText(_translate("DialogAnalysis", "To date"))
        self.label.setText(_translate("DialogAnalysis", "From date"))
        self.groupBox_6.setTitle(_translate("DialogAnalysis", "Sender recepian"))
        self.label_3.setText(_translate("DialogAnalysis", "Sender"))
        self.label_4.setText(_translate("DialogAnalysis", "recepian"))
        self.label_6.setText(_translate("DialogAnalysis", "This is"))
        self.label_13.setText(_translate("DialogAnalysis", "case!"))
        
        name = ['aaaa','baaa']
        for I in viber.selectAllViber(self):
            completer = QtWidgets.QCompleter(I.viberNumber)
        # put the completer in
        self.lineEdit_Recepian.setCompleter(completer)
        completer.data(CustomObjectRole)
         # put the completer in
        self.lineEdit_Sender.setCompleter(completer)
        
        # to date functionality
        self.dateEdit_dateFrom.setCalendarPopup(True)
        self.dateEdit_dateFrom.setMinimumDate(QtCore.QDate(2022, 2, 2))
        self.dateEdit_dateFrom.setMaximumDate(QtCore.QDate(2022, 3, 1))
        self.dateEdit_dateFrom.dateChanged.connect(self.fromlinedittopython)
        
        # to date functionality
        self.dateEdit_dateTo.setCalendarPopup(True)
        self.dateEdit_dateTo.setMinimumDate(QtCore.QDate(2022, 2, 2))
        self.dateEdit_dateTo.setMaximumDate(QtCore.QDate(2022, 3, 1))
        self.dateEdit_dateTo.dateChanged.connect(self.fromlinedittopython)
        self.dateEdit_dateTo.dateTimeChanged.connect(lambda: method(self))
        # btn screen shot
        self.btnSnapshot.clicked.connect(self.screenshoting)
       
         # btns for socialnetwork
        self.btn_Circular_Layout.clicked.connect(self.curcularlayout)
        self.btn_Planer_Layout.clicked.connect(self.planerlayout)
        self.btn_Random_Layout.clicked.connect(self.randomLayout)
        self.btn_Special_Layout.clicked.connect(self.spectralLayout)
        # btn for statistic
        self.btnBarChart.clicked.connect(self.barchart)
        self.btnPieChart.clicked.connect(self.piechart)
        self.checked()
        def method(self):
            print(self.dateEdit_dateTo.date())
    def listwidgetclicked(self,item):
        obj = completer.data(CustomObjectRole)
        self.viber = obj
    def fromlinedittopython(self):
        return self.dateEdit_dateTo.date().toPyDate

    def checked(self):
        if self.checkBox_Email.checkState() == 0:
            print('noemail')
        if self.checkBox_Email.checkState() == 2:
            print('email')
        if self.checkBox_Viber.checkState() == 0:
            print(' ')
        if self.checkBox_Viber.checkState() == 2:
            viber.selectAllViber()
        if self.checkBox_WhatsApp.checkState() == 0:
            print('noWATSUP')
        if self.checkBox_Viber.checkState() == 2:
            print('WATSUP')
    def curcularlayout(self):
        self.lbl_Visualization.setPixmap(
            QtGui.QPixmap("C:\\Users\\samar\\Desktop\\finalyearproject\\pythonProject1\\view\\filename1.png"))

    def planerlayout(self):
        self.lbl_Visualization.setPixmap(
            QtGui.QPixmap("C:\\Users\\samar\\Desktop\\finalyearproject\\pythonProject1\\view\\filename2.png"))

    def randomLayout(self):
        self.lbl_Visualization.setPixmap(
            QtGui.QPixmap("C:\\Users\\samar\\Desktop\\finalyearproject\\pythonProject1\\view\\filename3.png"))

    def spectralLayout(self):
        self.lbl_Visualization.setPixmap(
            QtGui.QPixmap("C:\\Users\\samar\\Desktop\\finalyearproject\\pythonProject1\\view\\filename4.png"))

    # btn to draw the stastic
    def piechart(self):
        self.lbl_statistic.setPixmap(
            QtGui.QPixmap("C:\\Users\\samar\\Desktop\\finalyearproject\\pythonProject1\\view\\f.png"))

    def barchart(self):
        self.lbl_statistic.setPixmap(
            QtGui.QPixmap("C:\\Users\\samar\\Desktop\\finalyearproject\\pythonProject1\\view\\barchart.png"))

    def screenshoting(self):
        im = PIL.ImageGrab.grab()
        im.save('snapshot.png')
        im.show()
        fileFilter = 'PNG (*.png)'
        options = QtWidgets.QFileDialog.getSaveFileName(caption='select a file', directory=' ', filter=fileFilter,
                                                        initialFilter='PNG (*.png)')

        if options:
            im.save(str(options))

    def getsavefilename(self):
        fileFilter = 'PNG (*.png)'
        response = QtWidgets.QFileDialog.getSaveFileName(caption='select a file', directory='snapshot.png',
                                                         filter=fileFilter, initialFilter=' JPG (*.png) '
                                                         )
        response = QtWidgets.QFileDialog.DontUseNativeDialog
        response = QtWidgets.QFileDialog.saveFileContent(self.screenshoting)
        return response


    def grapaDate(self):
        self.dateEdit_dateTo.setDate()
        print("ddd")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogAnalysis = QtWidgets.QDialog()
    ui = Ui_DialogAnalysis()
    ui.setupUi(DialogAnalysis)
    DialogAnalysis.show()
    sys.exit(app.exec_())
