# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\samar\Desktop\finalyearproject\pythonProject1\view\casesList.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from ast import Import
from PyQt5 import QtCore, QtGui, QtWidgets
from login import *

from Analysis17 import *
from examiners import ExaMiners
from cases import *


CustomObjectRole=QtCore.Qt.UserRole + 1

class Ui_CasesList(object):
    def openwindow(self):
       self.window = QtWidgets.QDialog() 
       self.ui= Ui_DialogAnalysis(self.SelectedCase)
       self.ui.setupUi(self.window)
       self.CasesList.hide()
       self.window.show()
    def openBackwindow(self):
        self.window = QtWidgets.QDialog()
        self.ui= ui_Dialog()
        self.ui.setupui(self.window)
       # self.CasesList.hide()
        self.window.show()
           
    def __init__(self, ex = None):
        self.examiner = ExaMiners()
        super(Ui_CasesList,self).__init__()
        if ex == None:
           return
        
        self.Examiner = ex
        self.selectedCase = cases()
              

   
    
    
    @property
    def Examiner(self):
        return self.examiner

    @Examiner.setter
    def Examiner(self, value):
        self.examiner = value

    @property
    def SelectedCase(self):
        return self.selectedCase

    @SelectedCase.setter
    def SelectedCase(self, value):
        self.selectedCase = value

    def setupUi(self, CasesList):
        CasesList.setObjectName("CasesList")
        CasesList.resize(674, 550)
        CasesList.setAutoFillBackground(True)
        CasesList.setSizeGripEnabled(True)
        self.LwCases = QtWidgets.QListWidget(CasesList)
        self.LwCases.setGeometry(QtCore.QRect(80, 80, 481, 341))
        self.LwCases.setObjectName("LwCases")
        self.BtnBack = QtWidgets.QPushButton(CasesList)
        self.BtnBack.setGeometry(QtCore.QRect(20, 480, 93, 28))
        self.BtnBack.setObjectName("BtnBack")
        self.BtnNext = QtWidgets.QPushButton(CasesList)
        self.BtnNext.setGeometry(QtCore.QRect(520, 490, 93, 28))
        self.BtnNext.setObjectName("BtnNext")
        self.lbl_caseliost = QtWidgets.QLabel(CasesList)
        self.lbl_caseliost.setGeometry(QtCore.QRect(70, 10, 181, 41))
        self.lbl_caseliost.setText("")
        self.lbl_caseliost.setObjectName("lbl_caseliost")
        #self.LwCases.addItem('dfdf')
        self.lbl_caseliost.setText(self.Examiner.firstName)
        
        

        for I in cases.getAll(self,self.Examiner.userId):
                item = QtWidgets.QListWidgetItem(I.caseName)
                self.LwCases.addItem(item)
                item.setData(CustomObjectRole,I)
        
        #self.LwCases.addItem(str(cases.getAll(self.ex.)))
        self.LwCases.itemClicked.connect(self.listwidgetclicked)
        self.BtnNext.clicked.connect(self.openwindow)
        self.BtnBack.clicked.connect(self.openBackwindow)


        self.retranslateUi(CasesList)
        QtCore.QMetaObject.connectSlotsByName(CasesList)

    def listwidgetclicked(self,item):
        obj = item.data(CustomObjectRole)
        self.SelectedCase = obj
          
    def retranslateUi(self, CasesList):
        _translate = QtCore.QCoreApplication.translate
        CasesList.setWindowTitle(_translate("CasesList", "Cases List"))
        self.BtnBack.setText(_translate("CasesList", "Back"))
        self.BtnNext.setText(_translate("CasesList", "Next"))
   

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CasesList = QtWidgets.QDialog()
    ui = Ui_CasesList()
    ui.setupUi(CasesList)
    CasesList.show()
    sys.exit(app.exec_())
