# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\samar\Desktop\finalyearproject\pythonProject1\view\casesList.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from ast import Import, Not, Try
from cProfile import label
from turtle import goto
from PyQt5 import QtCore, QtGui, QtWidgets
from pandas import isnull
from pyparsing import CaselessLiteral
from login import *

from Analysis19 import *
from examiners import ExaMiners
from cases import *
import time
from PyQt5.QtWidgets import QMessageBox


CustomObjectRole=QtCore.Qt.UserRole + 1

class Ui_CasesList(object):

    def openwindow(self):
        self.window = QtWidgets.QDialog() 
        self.ui= Ui_DialogAnalysis(self.SelectedCase)
      
        try:
            self.ui.setupUi(self.window)
            self.window.show()
        except:
            pass
            self.label_errormsg.setText('Select case please.')
            print("put micro here")
           
        
    def openBackwindow(self):
        self.window = QtWidgets.QDialog()
        self.ui= Ui_DialogAnalysis
        self.ui.setupui(self.window)
        #CasesList.hide()
        self.window.show()
    
           
    def __init__(self, ex = None):
        self.examiner = ExaMiners()
        super(Ui_CasesList,self).__init__()
        if ex == None:
           return
        
        self.Examiner = ex
        self.selectedCase = cases()
              

    def hidding(self):
       CasesList.hide()
    
    
    @property
    def Examiner(self):
        return self.examiner

    @Examiner.setter
    def Examiner(self, value):
        self.examiner = value

    @property
    def SelectedCase(self):
        return self.selectedCase

    @SelectedCase.setter
    def SelectedCase(self, value):
        self.selectedCase = value
        
 
       
    def setupUi(self, CasesList):
        CasesList.setObjectName("CasesList")
        CasesList.resize(674, 550)
        CasesList.setAutoFillBackground(True)
        CasesList.setSizeGripEnabled(True)
        CasesList.setStyleSheet("background-color: rgb(243, 247, 255);")
        self.LwCases = QtWidgets.QListWidget(CasesList)
        self.LwCases.setGeometry(QtCore.QRect(80, 80, 481, 341))
        self.LwCases.setObjectName("LwCases")
        
        self.LwCases.setCurrentRow(0)
        
        
        self.BtnBack = QtWidgets.QPushButton(CasesList)
        self.BtnBack.setStyleSheet("background-color: rgb(222, 223, 255);")
        self.BtnBack.setGeometry(QtCore.QRect(20, 480, 93, 28))
        self.BtnBack.setObjectName("BtnBack")
        self.BtnNext = QtWidgets.QPushButton(CasesList)
        self.BtnNext.setGeometry(QtCore.QRect(520, 490, 93, 28))
        self.BtnNext.setObjectName("BtnNext")
        self.BtnNext.setStyleSheet("background-color: rgb(222, 223, 255);")
        self.lbl_caseliost = QtWidgets.QLabel(CasesList)
        self.lbl_caseliost.setGeometry(QtCore.QRect(160, 10, 71, 41))
        self.lbl_caseliost.setObjectName("lbl_caseliost")
        self.lblwelcome = QtWidgets.QLabel(CasesList)
        self.lblwelcome.setGeometry(QtCore.QRect(30, 10, 101, 41))
        self.lblwelcome.setObjectName("lblwelcome")
        self.label_2 = QtWidgets.QLabel(CasesList)
        self.label_2.setGeometry(QtCore.QRect(240, 20, 20, 20))
        self.label_2.setObjectName("label_2")
        self.label_errormsg = QtWidgets.QLabel(CasesList)
        self.label_errormsg.setGeometry(QtCore.QRect(74, 440, 411, 20))
        self.label_errormsg.setObjectName("label_errormsg")
        #self.LwCases.addItem('dfdf')
        self.lbl_caseliost.setText(self.Examiner.firstName)
    

        for I in cases.getAll(self,self.Examiner.userId):
                item = QtWidgets.QListWidgetItem(I.caseName)
                self.LwCases.addItem(item)
                item.setData(CustomObjectRole,I)
                self.LwCases.setCurrentRow(0)
                self.LwCases.currentRow()
               
        
        #self.LwCases.addItem(str(cases.getAll(self.ex.)))
      
        self.LwCases.itemClicked.connect(self.listwidgetclicked)
        
        self.BtnNext.clicked.connect(self.openwindow)
        #self.BtnBack.clicked.connect(self.openBackwindow)
        self.BtnBack.clicked.connect(self.hidding)

        self.retranslateUi(CasesList)
        QtCore.QMetaObject.connectSlotsByName(CasesList)

    def listwidgetclicked(self,item):
     
        obj = item.data(CustomObjectRole)
        self.SelectedCase = obj
     
       
          
    def retranslateUi(self, CasesList):
        _translate = QtCore.QCoreApplication.translate
        CasesList.setWindowTitle(_translate("CasesList", "Cases List"))
        self.BtnBack.setText(_translate("CasesList", "Back"))
        self.BtnNext.setText(_translate("CasesList", "Next"))
        self.lblwelcome.setText(_translate("CasesList", "Welcome back"))
        self.label_2.setText(_translate("CasesList", "!"))
        self.label_errormsg.setText(_translate("CasesList", " "))

    def clickMethod(self):
        QMessageBox.about(self, "Title", "Message")
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CasesList = QtWidgets.QDialog()
    ui = Ui_CasesList()
    ui.setupUi(CasesList)
    CasesList.show()
    sys.exit(app.exec_())
