# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\samar\Desktop\finalyearproject\pythonProject1\view\casesList.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CasesList(object):
    def setupUi(self, CasesList):
        CasesList.setObjectName("CasesList")
        CasesList.resize(670, 541)
        CasesList.setAutoFillBackground(True)
        CasesList.setSizeGripEnabled(True)
        self.LwCases = QtWidgets.QListWidget(CasesList)
        self.LwCases.setGeometry(QtCore.QRect(80, 80, 481, 341))
        self.LwCases.setObjectName("LwCases")
        self.BtnBack = QtWidgets.QPushButton(CasesList)
        self.BtnBack.setGeometry(QtCore.QRect(20, 480, 93, 28))
        self.BtnBack.setObjectName("BtnBack")
        self.BtnNext = QtWidgets.QPushButton(CasesList)
        self.BtnNext.setGeometry(QtCore.QRect(520, 490, 93, 28))
        self.BtnNext.setObjectName("BtnNext")
        self.lbl_caseliost = QtWidgets.QLabel(CasesList)
        self.lbl_caseliost.setGeometry(QtCore.QRect(160, 10, 71, 41))
        self.lbl_caseliost.setObjectName("lbl_caseliost")
        self.lblwelcome = QtWidgets.QLabel(CasesList)
        self.lblwelcome.setGeometry(QtCore.QRect(30, 10, 101, 41))
        self.lblwelcome.setObjectName("lblwelcome")
        self.label_2 = QtWidgets.QLabel(CasesList)
        self.label_2.setGeometry(QtCore.QRect(240, 20, 20, 20))
        self.label_2.setObjectName("label_2")
        self.label_errormsg = QtWidgets.QLabel(CasesList)
        self.label_errormsg.setGeometry(QtCore.QRect(74, 440, 411, 20))
        self.label_errormsg.setObjectName("label_errormsg")

        self.retranslateUi(CasesList)
        QtCore.QMetaObject.connectSlotsByName(CasesList)

    def retranslateUi(self, CasesList):
        _translate = QtCore.QCoreApplication.translate
        CasesList.setWindowTitle(_translate("CasesList", "Cases List"))
        self.BtnBack.setText(_translate("CasesList", "Back"))
        self.BtnNext.setText(_translate("CasesList", "Next"))
        self.lbl_caseliost.setText(_translate("CasesList", "watson"))
        self.lblwelcome.setText(_translate("CasesList", "Welcome back"))
        self.label_2.setText(_translate("CasesList", "!"))
        self.label_errormsg.setText(_translate("CasesList", " "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CasesList = QtWidgets.QDialog()
    ui = Ui_CasesList()
    ui.setupUi(CasesList)
    CasesList.show()
    sys.exit(app.exec_())
