# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Examiner.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Model.connection
import examiners


class Ui_Dialog(object):


    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1006, 651)
        Dialog.setAutoFillBackground(False)
        Dialog.setStyleSheet("font-size:12pt")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(360, 70, 881, 101))
        self.label_3.setStyleSheet("font-size:14pt")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(40, 250, 161, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(40, 340, 151, 20))
        self.label_5.setObjectName("label_5")

        self.lnEdtPhone = QtWidgets.QLineEdit(Dialog)
        self.lnEdtPhone.setGeometry(QtCore.QRect(200, 340, 601, 22))
        self.lnEdtPhone.setObjectName("lnEdtPhone")
        print(self.lnEdtPhone.text())
    #self.lnEdtPhone.activated.connect(self.findExaminerID)

        #examiners.ExaMiners.bein(self.lnEdtPhone.text())
        self.BtnNextExaminer = QtWidgets.QPushButton(Dialog)
        self.BtnNextExaminer.setGeometry(QtCore.QRect(530, 600, 93, 28))
        self.BtnNextExaminer.setObjectName("BtnNextExaminer")
        self.BtnFinshExaminer = QtWidgets.QPushButton(Dialog)
        self.BtnFinshExaminer.setGeometry(QtCore.QRect(270, 600, 93, 28))
        self.BtnFinshExaminer.setObjectName("BtnFinshExaminer")
        self.BtnHelpExaminer = QtWidgets.QPushButton(Dialog)
        self.BtnHelpExaminer.setGeometry(QtCore.QRect(900, 610, 93, 28))
        self.BtnHelpExaminer.setObjectName("BtnHelpExaminer")
        self.BtnCancleExaminer = QtWidgets.QPushButton(Dialog)
        self.BtnCancleExaminer.setGeometry(QtCore.QRect(30, 600, 93, 28))
        self.BtnCancleExaminer.setObjectName("BtnCancleExaminer")
        self.BtnCancleExaminer.clicked.connect(self.findExaminerID)

        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(210, 250, 601, 22))
        self.comboBox.setObjectName("comboBox")

        self.comboBox.activated.connect(self.findExaminer)
        self.BtnCancleExaminer.clicked.connect(self.findExaminerID)

        self.BtnNextExaminer.clicked.connect(self.bein)

        print('details')
        for i in range(len(examiners.ex.Details())):
            p= [examiners.ex.fulName(examiners.ex.Details()[i][0],examiners.ex.Details()[i][1])]
            self.comboBox.addItems(p)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
    #getting the current selected name from the combobox

    def findExaminer(self):
         print(str(self.comboBox.currentText()))
    def findExaminerID(self):
        print(self.lnEdtPhone.text())
    def firsttNames(self):
        fullname = str(self.comboBox.currentText())
        spil = ' '
        res = fullname.split(spil)
        print(res)
        fn =[]
        return res[0]

    def lastNames(self):
        fullname = str(self.comboBox.currentText())
        spil = ' '
        res = fullname.split(spil)
        print(res)
        return res[0]

    def bein(self):
        w = Model.connection.conection.mycursor.callproc('casesforinvestigators', [self.findExaminerID, ])
        Model.connection.conection.mycursor.stored_results()
        cases = []
        mf = []
        for result in Model.connection.conection.mycursor.stored_results():
            temp = result.fetchall()
            return temp

    def login(self):
        w = Model.connection.conection.mycursor.callproc('procLogin', [self.firsttNames,], [self.lastNames,],
                                                        [self.findExaminerID,])
        Model.connection.conection.mycursor.stored_results()
        cases = []
        mf = []
        for result in Model.connection.conection.mycursor.stored_results():
            temp = result.fetchall()
            return temp













    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Examiner</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "Examiner Name"))
        self.label_5.setText(_translate("Dialog", "Examiner number"))
        self.BtnNextExaminer.setText(_translate("Dialog", "Next"))
        self.BtnFinshExaminer.setText(_translate("Dialog", "Finish"))
        self.BtnHelpExaminer.setText(_translate("Dialog", "Help"))
        self.BtnCancleExaminer.setText(_translate("Dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

