# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Examiner.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets

from view.case import Ui_NewCaseINformation


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1006, 651)
        Dialog.setStyleSheet("font-size:12pt")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(44, 120, 131, 20))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(410, 190, 711, 16))
        self.label_3.setStyleSheet("font-size:14pt")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(40, 250, 161, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(40, 290, 151, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(40, 330, 161, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(80, 390, 61, 19))
        self.label_7.setObjectName("label_7")
        self.lnEdtCaseName = QtWidgets.QLineEdit(Dialog)
        self.lnEdtCaseName.setGeometry(QtCore.QRect(180, 120, 621, 22))
        self.lnEdtCaseName.setObjectName("lnEdtCaseName")
        self.lneEdtExaminerName = QtWidgets.QLineEdit(Dialog)
        self.lneEdtExaminerName.setGeometry(QtCore.QRect(210, 250, 611, 22))
        self.lneEdtExaminerName.setObjectName("lneEdtExaminerName")
        self.lnEdtPhone = QtWidgets.QLineEdit(Dialog)
        self.lnEdtPhone.setGeometry(QtCore.QRect(210, 290, 611, 22))
        self.lnEdtPhone.setObjectName("lnEdtPhone")
        self.LnEditEmail = QtWidgets.QLineEdit(Dialog)
        self.LnEditEmail.setGeometry(QtCore.QRect(210, 330, 611, 22))
        self.LnEditEmail.setObjectName("LnEditEmail")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(450, 80, 71, 20))
        self.label_2.setStyleSheet("font-size:14pt")
        self.label_2.setObjectName("label_2")
        self.BtnNextExaminer = QtWidgets.QPushButton(Dialog)
        self.BtnNextExaminer.setGeometry(QtCore.QRect(400, 590, 93, 28))
        self.BtnNextExaminer.setObjectName("BtnNextExaminer")
        self.BtnBackExaminer = QtWidgets.QPushButton(Dialog)
        self.BtnBackExaminer.setGeometry(QtCore.QRect(300, 590, 93, 28))
        self.BtnBackExaminer.setObjectName("BtnBackExaminer")
        self.BtnFinshExaminer = QtWidgets.QPushButton(Dialog)
        self.BtnFinshExaminer.setGeometry(QtCore.QRect(510, 590, 93, 28))
        self.BtnFinshExaminer.setObjectName("BtnFinshExaminer")
        self.BtnHelpExaminer = QtWidgets.QPushButton(Dialog)
        self.BtnHelpExaminer.setGeometry(QtCore.QRect(740, 590, 93, 28))
        self.BtnHelpExaminer.setObjectName("BtnHelpExaminer")
        self.BtnCancleExaminer = QtWidgets.QPushButton(Dialog)
        self.BtnCancleExaminer.setGeometry(QtCore.QRect(620, 590, 93, 28))
        self.BtnCancleExaminer.setObjectName("BtnCancleExaminer")
        self.TxtEdtNote = QtWidgets.QTextEdit(Dialog)
        self.TxtEdtNote.setGeometry(QtCore.QRect(200, 380, 641, 87))
        self.TxtEdtNote.setObjectName("TxtEdtNote")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(240, 500, 211, 20))
        self.label_8.setObjectName("label_8")
        self.BtnUploadCace = QtWidgets.QPushButton(Dialog)
        self.BtnUploadCace.setGeometry(QtCore.QRect(450, 500, 241, 28))
        self.BtnUploadCace.setObjectName("BtnUploadCace")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.BtnBackExaminer.clicked.connect(self.backpage)
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Case Number"))
        self.label_3.setText(_translate("Dialog", "Examiner"))
        self.label_4.setText(_translate("Dialog", "Examiner Name"))
        self.label_5.setText(_translate("Dialog", "Examiner phone "))
        self.label_6.setText(_translate("Dialog", "Examiner email"))
        self.label_7.setText(_translate("Dialog", "Note"))
        self.label_2.setText(_translate("Dialog", "Case"))
        self.BtnNextExaminer.setText(_translate("Dialog", "Next"))
        self.BtnBackExaminer.setText(_translate("Dialog", "Back"))
        self.BtnFinshExaminer.setText(_translate("Dialog", "Finish"))
        self.BtnHelpExaminer.setText(_translate("Dialog", "Help"))
        self.BtnCancleExaminer.setText(_translate("Dialog", "Cancel"))
        self.TxtEdtNote.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_8.setText(_translate("Dialog", "upload the case file "))
        self.BtnUploadCace.setText(_translate("Dialog", "The Case File"))

    def backpage(self):
          self.NewCaseINformation = QtWidgets.QDialog()
          self.ui = Ui_NewCaseINformation()
          self.ui.setupUi(self.NewCaseINformation)
          self.NewCaseINformation.show()
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
