# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\samar\Desktop\finalyearproject\pythonProject1\view\logbook.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_logBook(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(830, 398)
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 791, 261))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lbl_fileName = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_fileName.setObjectName("lbl_fileName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_fileName)
        self.lineEdit_fIstName = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_fIstName.setObjectName("lineEdit_fIstName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_fIstName)
        self.lineEdit_BookmarkNumber = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_BookmarkNumber.setObjectName("lineEdit_BookmarkNumber")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_BookmarkNumber)
        self.lineEdit_to = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_to.setObjectName("lineEdit_to")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_to)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.lineEdit_from = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_from.setObjectName("lineEdit_from")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_from)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.lineEdit_cc = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_cc.setObjectName("lineEdit_cc")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_cc)
        self.lineEdit_senderNumber = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_senderNumber.setObjectName("lineEdit_senderNumber")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_senderNumber)
        self.lineEdit_BCC = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_BCC.setObjectName("lineEdit_BCC")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_BCC)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_RecepiantNumber = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_RecepiantNumber.setObjectName("lineEdit_RecepiantNumber")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit_RecepiantNumber)
        self.btnBack = QtWidgets.QPushButton(Dialog)
        self.btnBack.setGeometry(QtCore.QRect(60, 310, 93, 28))
        self.btnBack.setObjectName("btnBack")
        self.BtnNext = QtWidgets.QPushButton(Dialog)
        self.BtnNext.setGeometry(QtCore.QRect(650, 320, 93, 28))
        self.BtnNext.setObjectName("BtnNext")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "booklog_Details"))
        self.lbl_fileName.setText(_translate("Dialog", " File Name"))
        self.label_8.setText(_translate("Dialog", " BookMark Number"))
        self.label_11.setText(_translate("Dialog", " To"))
        self.label_10.setText(_translate("Dialog", " From"))
        self.label_12.setText(_translate("Dialog", " cc"))
        self.label_13.setText(_translate("Dialog", " BCC"))
        self.label.setText(_translate("Dialog", " Sender number"))
        self.label_2.setText(_translate("Dialog", " Resepient number"))
        self.btnBack.setText(_translate("Dialog", "Back"))
        self.BtnNext.setText(_translate("Dialog", "Next"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_logBook()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
