# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\samar\Desktop\finalyearproject\pythonProject1\login.ui'
#
# Created by: PyQt5 ui code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from casesList import *
import examiners
from cases import *
#from casesList import Ui_CasesList

class ui_Dialog(object):
    def NextWindow(self):
        # the log in is not working
       
        ex = examiners.ExaMiners.anotherlogin(self,self._LnEditName.text(), self.lnEditPassword.text())
        self.window = QtWidgets.QDialog()
        self.ui= Ui_CasesList(ex)
        self.ui.setupUi(self.window)
        Dialog.hide()
        self.window.show()
      

           
    def setupui(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1006, 651)
        Dialog.setAutoFillBackground(False)
        Dialog.setStyleSheet("font-size:12pt")
        self.lblloginTitle = QtWidgets.QLabel(Dialog)
        self.lblloginTitle.setGeometry(QtCore.QRect(60, 90, 881, 101))
        self.lblloginTitle.setStyleSheet("font-size:14pt")
        self.lblloginTitle.setObjectName("lblloginTitle")
        self.LblPassword = QtWidgets.QLabel(Dialog)
        self.LblPassword.setGeometry(QtCore.QRect(40, 330, 151, 41))
        self.LblPassword.setObjectName("LblPassword")
        self.lnEditPassword = QtWidgets.QLineEdit(Dialog)
        self.lnEditPassword.setGeometry(QtCore.QRect(200, 340, 601, 22))
        self.lnEditPassword.setObjectName("lnEditPassword")
        self.lnEditPassword.setEchoMode(self.lnEditPassword.Password)
        
        self.BtnLogin = QtWidgets.QPushButton(Dialog)
        self.BtnLogin.setGeometry(QtCore.QRect(730, 570, 241, 51))
        self.BtnLogin.setObjectName("BtnLogin")
        self.BtnLogin.clicked.connect(self.NextWindow)
        self.BtnCancleExaminer = QtWidgets.QPushButton(Dialog)
        self.BtnCancleExaminer.setGeometry(QtCore.QRect(30, 577, 221, 51))
        self.BtnCancleExaminer.setObjectName("BtnCancleExaminer")
        self._LnEditName = QtWidgets.QLineEdit(Dialog)
        self._LnEditName.setGeometry(QtCore.QRect(200, 250, 591, 22))
        self._LnEditName.setObjectName("_LnEditName")
        self.LblUserName = QtWidgets.QLabel(Dialog)
        self.LblUserName.setGeometry(QtCore.QRect(40, 250, 101, 20))
        self.LblUserName.setToolTipDuration(-2)
        self.LblUserName.setObjectName("LblUserName")
        self.BtnCancleExaminer.clicked.connect(Dialog.close)
        self.lblmsg = QtWidgets.QLabel(Dialog)
        self.lblmsg.setGeometry(QtCore.QRect(170, 425, 631, 61))
        self.lblmsg.setText("")
        self.lblmsg.setObjectName("lblmsg")

        self.retranslateui(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateui(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lblloginTitle.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Login</span></p></body></html>"))
        self.LblPassword.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Password</span></p></body></html>"))
        self.BtnLogin.setText(_translate("Dialog", "Log in"))
        self.BtnCancleExaminer.setText(_translate("Dialog", "Cancel"))
        self.LblUserName.setText(_translate("Dialog", "<html><head/><body><p>User name</p></body></html>"))
        self.lblmsg.setText(_translate("Dialog", " "))

    

   
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = ui_Dialog()
    ui.setupui(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
