# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analy.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from ast import Import
from datetime import date


import os
from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtCore import QDate, QTime, QDateTime, Qt
import PIL.ImageGrab
from PyQt5.QtWebEngineWidgets import QWebEngineView
from GeographicalLocation import *



class Ui_MainWindow(object):
   
    def setupUi(self, MainWindow):
       

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1323, 918)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidgetBookMark = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidgetBookMark.setGeometry(QtCore.QRect(0, 0, 1011, 931))
        self.tabWidgetBookMark.setObjectName("tabWidgetBookMark")
        self.geoloctab = QtWidgets.QWidget()
        self.geoloctab.setObjectName("geoloctab")
        self.tabWidgetBookMark.addTab(self.geoloctab, "")
        self.webEngineView = QtWidgets.QWebEngineView()

        
        self.SocialNetworktab = QtWidgets.QWidget()
        self.SocialNetworktab.setObjectName("SocialNetworktab")
        self.lbl_Visualization = QtWidgets.QLabel(self.SocialNetworktab)
        self.lbl_Visualization.setGeometry(QtCore.QRect(14, 20, 971, 711))
        self.lbl_Visualization.setText("")
        self.lbl_Visualization.setPixmap(QtGui.QPixmap("C:\\Users\\samar\\Desktop\\finalyearproject\\pythonProject1\\view\\filename4.png"))
        self.lbl_Visualization.setScaledContents(True)
        self.lbl_Visualization.setObjectName("lbl_Visualization")
        self.groupBox_7 = QtWidgets.QGroupBox(self.SocialNetworktab)
        self.groupBox_7.setGeometry(QtCore.QRect(30, 780, 751, 80))
        self.groupBox_7.setObjectName("groupBox_7")
        self.btn_Circular_Layout = QtWidgets.QPushButton(self.groupBox_7)
        self.btn_Circular_Layout.setGeometry(QtCore.QRect(30, 30, 93, 28))
        self.btn_Circular_Layout.setObjectName("btn_Circular_Layout")
        self.btn_Planer_Layout = QtWidgets.QPushButton(self.groupBox_7)
        self.btn_Planer_Layout.setGeometry(QtCore.QRect(130, 30, 93, 28))
        self.btn_Planer_Layout.setObjectName("btn_Planer_Layout")
        self.btn_Random_Layout = QtWidgets.QPushButton(self.groupBox_7)
        self.btn_Random_Layout.setGeometry(QtCore.QRect(230, 30, 93, 28))
        self.btn_Random_Layout.setObjectName("btn_Random_Layout")
        self.btn_Special_Layout = QtWidgets.QPushButton(self.groupBox_7)
        self.btn_Special_Layout.setGeometry(QtCore.QRect(340, 30, 93, 28))
        self.btn_Special_Layout.setObjectName("btn_Special_Layout")
        self.tabWidgetBookMark.addTab(self.SocialNetworktab, "")
        self.statisictap = QtWidgets.QWidget()
        self.statisictap.setObjectName("statisictap")
        self.groupBox_4 = QtWidgets.QGroupBox(self.statisictap)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 790, 791, 80))
        self.groupBox_4.setObjectName("groupBox_4")
        self.btnPieChart = QtWidgets.QPushButton(self.groupBox_4)
        self.btnPieChart.setGeometry(QtCore.QRect(70, 20, 93, 28))
        self.btnPieChart.setObjectName("btnPieChart")
        self.btnBarChart = QtWidgets.QPushButton(self.groupBox_4)
        self.btnBarChart.setGeometry(QtCore.QRect(210, 20, 93, 28))
        self.btnBarChart.setObjectName("btnBarChart")
        self.checkBox_places = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_places.setGeometry(QtCore.QRect(410, 20, 81, 20))
        self.checkBox_places.setObjectName("checkBox_places")
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_5.setGeometry(QtCore.QRect(530, 20, 81, 20))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_6.setGeometry(QtCore.QRect(670, 20, 81, 20))
        self.checkBox_6.setObjectName("checkBox_6")
        self.lbl_statistic = QtWidgets.QLabel(self.statisictap)
        self.lbl_statistic.setGeometry(QtCore.QRect(20, 20, 761, 751))
        self.lbl_statistic.setText("")
        self.lbl_statistic.setPixmap(QtGui.QPixmap("C:\\Users\\samar\\Desktop\\finalyearproject\\pythonProject1\\view\\barchart.png"))
        self.lbl_statistic.setScaledContents(True)
        self.lbl_statistic.setObjectName("lbl_statistic")
        self.tabWidgetBookMark.addTab(self.statisictap, "")
        self.tab_tap = QtWidgets.QWidget()
        self.tab_tap.setObjectName("tab_tap")
        self.label_5 = QtWidgets.QLabel(self.tab_tap)
        self.label_5.setGeometry(QtCore.QRect(-20, -10, 951, 841))
        self.label_5.setObjectName("label_5")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_tap)
        self.plainTextEdit.setGeometry(QtCore.QRect(0, 10, 961, 851))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.tabWidgetBookMark.addTab(self.tab_tap, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidgetBookMark.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_analysis = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_analysis.setStyleSheet("q rgb(250, 235, 255)")
        self.dockWidget_analysis.setObjectName("dockWidget_analysis")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.dockWidgetContents_2)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 140, 211, 151))
        self.groupBox_2.setObjectName("groupBox_2")
        self.checkBox_Email = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_Email.setGeometry(QtCore.QRect(30, 40, 81, 20))
        self.checkBox_Email.setObjectName("checkBox_Email")
        self.checkBox_WhatsApp = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_WhatsApp.setGeometry(QtCore.QRect(30, 70, 81, 20))
        self.checkBox_WhatsApp.setObjectName("checkBox_WhatsApp")
        self.checkBox_Viber = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_Viber.setGeometry(QtCore.QRect(30, 110, 81, 20))
        self.checkBox_Viber.setObjectName("checkBox_Viber")
        #search a keyword
        self.lineEdit_serchKeyWord_ForChat = QtWidgets.QLineEdit(self.dockWidgetContents_2)
        self.lineEdit_serchKeyWord_ForChat.setGeometry(QtCore.QRect(120, 90, 161, 31))
        self.lineEdit_serchKeyWord_ForChat.setObjectName("lineEdit_serchKeyWord_ForChat")
        
        

        self.btnKeyWordChat_2 = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.btnKeyWordChat_2.setGeometry(QtCore.QRect(10, 90, 111, 31))
        self.btnKeyWordChat_2.setObjectName("btnKeyWordChat_2")
        self.btnKeyWordChat_2.clicked.connect(self.fromlinedittopython)
        #self.btnKeyWordChat_2.clicked.connect(self.search)
        self.btnSnapshot = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.btnSnapshot.setGeometry(QtCore.QRect(20, 10, 61, 51))
        self.btnSnapshot.setObjectName("btnSnapshot")
        self.btnSnapshot.clicked.connect(self.screenshoting)
        self.groupBox_3 = QtWidgets.QGroupBox(self.dockWidgetContents_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 640, 231, 81))
        self.groupBox_3.setObjectName("groupBox_3")
        self.checkBox_filterKeyWord = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_filterKeyWord.setGeometry(QtCore.QRect(10, 20, 201, 20))
        self.checkBox_filterKeyWord.setObjectName("checkBox_filterKeyWord")
        self.checkBox_FiterTimeDate = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_FiterTimeDate.setGeometry(QtCore.QRect(10, 50, 171, 20))
        self.checkBox_FiterTimeDate.setObjectName("checkBox_FiterTimeDate")
        self.btnVerify = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.btnVerify.setGeometry(QtCore.QRect(40, 760, 141, 28))
        self.btnVerify.setObjectName("btnVerify")
        self.groupBox_5 = QtWidgets.QGroupBox(self.dockWidgetContents_2)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 300, 271, 101))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setGeometry(QtCore.QRect(10, 20, 61, 20))
        self.label.setObjectName("label")
        #date
        self.dateEdit_dateFrom = QtWidgets.QDateEdit(self.groupBox_5)
        self.dateEdit_dateFrom.setGeometry(QtCore.QRect(80, 20, 110, 22))
        self.dateEdit_dateFrom.setObjectName("dateEdit_dateFrom")
        #setting the calinder

        self.dateEdit_dateFrom.setCalendarPopup(True)
        self.dateEdit_dateTo = QtWidgets.QDateEdit(self.groupBox_5)
        self.dateEdit_dateTo.setGeometry(QtCore.QRect(80, 60, 110, 22))
        self.dateEdit_dateTo.setObjectName("dateEdit_dateTo")
        self.dateEdit_dateTo.dateTimeChanged.connect(lambda: method(self))
        

        #highlight the available dates
       # self.dateEdit_dateFrom.setDateRange(QtCore.QDate(2022,2,2),QtCore.QDate(2022,3,1))
        #setting the calinder
        # self.dateEdit_dateFrom.setGridVisible(True)
        self.dateEdit_dateTo.dateChanged.connect(self.fromlinedittopython)
        # print("change!!")
        self.dateEdit_dateTo.setMinimumDate(QtCore.QDate(2022,2,2))
        self.dateEdit_dateTo.setMaximumDate(QtCore.QDate(2022,3,1))
        self.dateEdit_dateTo.setCalendarPopup(True)
       
        
        
        
        





       
        
        
        
       
       
        
        
         

       # self.btnVerify.clicked.connect(self.getsavefilename)


        self.groupBox_6 = QtWidgets.QGroupBox(self.dockWidgetContents_2)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 460, 241, 80))
        self.groupBox_6.setObjectName("groupBox_6")
        #add completer to the line editor
        name = ['apple', 'ape', 'boo', 'baa', 'bee']
        completer = QtWidgets.QCompleter(name)
        self.lineEdit_Sender = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_Sender.setGeometry(QtCore.QRect(70, 20, 161, 22))
        self.lineEdit_Sender.setObjectName("lineEdit_Sender")
        #put the completer in
        self.lineEdit_Sender.setCompleter(completer)
        self.label_3 = QtWidgets.QLabel(self.groupBox_6)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 55, 16))
        self.label_3.setObjectName("label_3")
        # add compter for the line editeors 
        self.lineEdit_Recepian = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_Recepian.setGeometry(QtCore.QRect(70, 50, 161, 22))
        self.lineEdit_Recepian.setObjectName("lineEdit_Recepian")
        #put the completer in
        self.lineEdit_Recepian.setCompleter(completer)
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 55, 21))
        self.label_4.setObjectName("label_4")
        self.dockWidget_analysis.setWidget(self.dockWidgetContents_2)
        
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_analysis)

        self.retranslateUi(MainWindow)
        self.tabWidgetBookMark.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidgetBookMark.setTabText(self.tabWidgetBookMark.indexOf(self.geoloctab), _translate("MainWindow", "Geolocation"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Virtualization  Social Network"))
        self.btn_Circular_Layout.setText(_translate("MainWindow", "Circular layout"))
        self.btn_Planer_Layout.setText(_translate("MainWindow", "Planer layout"))
        self.btn_Random_Layout.setText(_translate("MainWindow", "Random layout"))
        self.btn_Special_Layout.setText(_translate("MainWindow", "Spectral layout"))
        
        self.tabWidgetBookMark.setTabText(self.tabWidgetBookMark.indexOf(self.SocialNetworktab), _translate("MainWindow", "Social networ"))
        self.groupBox_4.setTitle(_translate("MainWindow", "options"))
        self.btnPieChart.setText(_translate("MainWindow", "Pie chart"))
        self.btnBarChart.setText(_translate("MainWindow", "Bar chart"))
        self.checkBox_places.setText(_translate("MainWindow", "Places"))
        self.checkBox_5.setText(_translate("MainWindow", "People"))
        self.checkBox_6.setText(_translate("MainWindow", "Dates"))
        self.tabWidgetBookMark.setTabText(self.tabWidgetBookMark.indexOf(self.statisictap), _translate("MainWindow", "statisic"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidgetBookMark.setTabText(self.tabWidgetBookMark.indexOf(self.tab_tap), _translate("MainWindow", "chat"))
        self.tabWidgetBookMark.setTabText(self.tabWidgetBookMark.indexOf(self.tab), _translate("MainWindow", "Bookmark"))
        self.dockWidget_analysis.setWindowTitle(_translate("MainWindow", "Analysis bar"))
        self.groupBox_2.setTitle(_translate("MainWindow", "platForm"))
        self.checkBox_Email.setText(_translate("MainWindow", "Email"))
        self.checkBox_WhatsApp.setText(_translate("MainWindow", "WahatApp"))
        self.checkBox_Viber.setText(_translate("MainWindow", "Viber"))
        self.btnKeyWordChat_2.setText(_translate("MainWindow", "Search keyword"))
        self.btnSnapshot.setText(_translate("MainWindow", "Snapshot"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Filter option"))
        self.checkBox_filterKeyWord.setText(_translate("MainWindow", "Filter by  keyword only"))
        self.checkBox_FiterTimeDate.setText(_translate("MainWindow", "Filter by Date and time only"))
        self.btnVerify.setText(_translate("MainWindow", "verify"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Date filtering"))
        self.label_2.setText(_translate("MainWindow", "To date"))
        self.label.setText(_translate("MainWindow", "From date"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Sender recepian"))
        self.label_3.setText(_translate("MainWindow", "Sender"))
        self.label_4.setText(_translate("MainWindow", "recepian"))
        # btns for socialnetwork
        self.btn_Circular_Layout.clicked.connect(self.curcularlayout)
        self.btn_Planer_Layout.clicked.connect(self.planerlayout)
        self.btn_Random_Layout.clicked.connect(self.randomLayout)
        self.btn_Special_Layout.clicked.connect(self.spectralLayout)
        #btn for statistic
        self.btnBarChart.clicked.connect(self.barchart)
        self.btnPieChart.clicked.connect(self.piechart)
        self.checked()
   
    
         
  
       

    # functions to draw  the socialNetoek 
    def fromlinedittopython(self):
        return self.dateEdit_dateTo.date().toPyDate
    def checked(self):
            if self.checkBox_Email.checkState()==0:
                 print('noemail')
            if self.checkBox_Email.checkState()==2:
                print('email')
            if  self.checkBox_WhatsApp.checkState()==0:
                print('noWATSUP')
            if  self.checkBox_WhatsApp.checkState()==2:
                 print(' WATSUP')
            if  self.checkBox_WhatsApp.checkState()==0:
                print('noWATSUP')
            if  self.checkBox_Viber.checkState()==2:
                 print('WATSUP')
    def curcularlayout(self):
        self.lbl_Visualization.setPixmap(QtGui.QPixmap("C:\\Users\\samar\\Desktop\\finalyearproject\\pythonProject1\\view\\filename1.png"))
    def planerlayout(self):
            self.lbl_Visualization.setPixmap(QtGui.QPixmap("C:\\Users\\samar\\Desktop\\finalyearproject\\pythonProject1\\view\\filename2.png"))
    def randomLayout(self):
            self.lbl_Visualization.setPixmap(QtGui.QPixmap("C:\\Users\\samar\\Desktop\\finalyearproject\\pythonProject1\\view\\filename3.png"))
    def spectralLayout(self):
            self.lbl_Visualization.setPixmap(QtGui.QPixmap("C:\\Users\\samar\\Desktop\\finalyearproject\\pythonProject1\\view\\filename4.png"))
    #btn to draw the stastic
    def piechart(self):
             self.lbl_statistic.setPixmap(QtGui.QPixmap("C:\\Users\\samar\\Desktop\\finalyearproject\\pythonProject1\\view\\f.png"))
            
    def barchart(self):
            self.lbl_statistic.setPixmap(QtGui.QPixmap("C:\\Users\\samar\\Desktop\\finalyearproject\\pythonProject1\\view\\barchart.png"))
           
   
        
    def screenshoting(self):
        im = PIL.ImageGrab.grab()
        im.save('snapshot.png')
        im.show() 
        fileFilter='PNG (*.png)'
        options=QtWidgets.QFileDialog.getSaveFileName(caption ='select a file', directory=' ', filter= fileFilter, initialFilter='PNG (*.png)')
           
        if options:
                im.save(str(options))
    
    def getsavefilename(self):
            fileFilter='PNG (*.png)'
            response=QtWidgets.QFileDialog.getSaveFileName( caption ='select a file', directory='snapshot.png', filter= fileFilter, initialFilter=' JPG (*.png) '
            )
            response=QtWidgets.QFileDialog.DontUseNativeDialog
            response=QtWidgets.QFileDialog.saveFileContent(self.screenshoting)
            return response
def grapaDate(self):
        self.dateEdit_dateTo.setDate()
        print("ddd")

def method(self):
       print(self.dateEdit_dateTo.date())
   
           
            

        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
